### ISSUE TITLE
Receiving an error on the user signup form

### ISSUE THREAD

**Issue by paragonn** [c10d-dev/craft-hcaptcha#4]
It looks like a table might be missing from the database. Please see the error log below.

Here is the error log:
2023-01-18 17:22:18 [-][-][ck82fs7961r5k85n4n2t5e37l8][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: The table does not exist: {{%crafthcaptcha_logs}} in /data/www/delve/production/vendor/yiisoft/yii2/db/ActiveRecord.php:442
Stack trace:
#0 /data/www/delve/production/vendor/yiisoft/yii2/db/ActiveRecord.php(473): yii\db\ActiveRecord::getTableSchema()
#1 /data/www/delve/production/vendor/yiisoft/yii2/db/BaseActiveRecord.php(498): yii\db\ActiveRecord->attributes()
#2 /data/www/delve/production/vendor/craftcms/cms/src/db/ActiveRecord.php(51): yii\db\BaseActiveRecord->hasAttribute()
#3 /data/www/delve/production/vendor/c10d/craft-hcaptcha/src/services/HcaptchaService.php(75): craft\db\ActiveRecord->__set()
#4 /data/www/delve/production/vendor/c10d/craft-hcaptcha/src/CraftHcaptcha.php(156): c10d\crafthcaptcha\services\HcaptchaService->verify()
#5 [internal function]: c10d\crafthcaptcha\CraftHcaptcha->c10d\crafthcaptcha\{closure}()
#6 /data/www/delve/production/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#7 /data/www/delve/production/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#8 /data/www/delve/production/vendor/yiisoft/yii2/base/Model.php(385): yii\base\Component->trigger()
#9 /data/www/delve/production/vendor/yiisoft/yii2/base/Model.php(350): yii\base\Model->beforeValidate()
#10 /data/www/delve/production/vendor/craftcms/cms/src/controllers/UsersController.php(1249): yii\base\Model->validate()
#11 [internal function]: craft\controllers\UsersController->actionSaveUser()
#12 /data/www/delve/production/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#13 /data/www/delve/production/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#14 /data/www/delve/production/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#15 /data/www/delve/production/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction()
#16 /data/www/delve/production/vendor/craftcms/cms/src/web/Application.php(602): craft\web\Application->runAction()
#17 /data/www/delve/production/vendor/craftcms/cms/src/web/Application.php(272): craft\web\Application->_processActionRequest()
#18 /data/www/delve/production/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#19 /data/www/delve/production/web/index.php(21): yii\base\Application->run()
#20 {main}
2023-01-18 17:22:18 [-][-][ck82fs7961r5k85n4n2t5e37l8][info][application] $_GET = [
    'p' => 'users/sign-up'
]

**Comment by paragonn** [comment]
Actually I resolved this issue by uninstalling and reinstalling the plugin.
